export const POSTS_FETCH_ALL = 'POSTS_FETCH_ALL';
export const POSTS_CREATE = 'POSTS_CREATE'
export const POSTS_UPDATE = 'POSTS_UPDATE'
export const POSTS_DELETE = 'POSTS_DELETE'
export const POSTS_LIKE = 'POSTS_LIKE'
export const POSTS_SEARCH = 'POSTS_SEARCH'
export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'